projects = {
    "libft": {
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "write": "unistd.h",
    },

    "get_next_line": {
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "read": "unistd.h",
    },
    "ft_printf": {
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "write": "unistd.h",
        "va_start": "stdarg.h",
        "va_arg": "stdarg.h",
        "va_copy": "stdarg.h",
        "va_end": "stdarg.h",
    },

    "push_swap": {
        "read": "unistd.h",
        "write": "unistd.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "exit": "stdlib.h",
    },
    "fract-ol": {
        "open": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "perror": "stdio.h",
        "strerror": "string.h",
        "exit": "stdlib.h",

        "sqrt": "math.h",
        "pow": "math.h",
        "fabs": "math.h",
        "sin": "math.h",
        "cos": "math.h",
        "tan": "math.h",

        "mlx_init": "mlx.h",
    },
    "fdf": {
        "open": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "perror": "stdio.h",
        "strerror": "string.h",
        "exit": "stdlib.h",

        "sqrt": "math.h",
        "pow": "math.h",
        "fabs": "math.h",
        "sin": "math.h",
        "cos": "math.h",
        "tan": "math.h",

        "mlx_init": "mlx.h",
    },
    "so-long": {
        "open": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "perror": "stdio.h",
        "strerror": "string.h",
        "exit": "stdlib.h",

        "sqrt": "math.h",
        "pow": "math.h",
        "fabs": "math.h",
        "sin": "math.h",
        "cos": "math.h",
        "tan": "math.h",

        "mlx_init": "mlx.h",
    },

    "minitalk": {
        "write": "unistd.h",
        "signal": "signal.h",
        "sigemptyset": "signal.h",
        "sigaddset": "signal.h",
        "sigaction": "signal.h",
        "kill": "signal.h",
        "getpid": "unistd.h",

        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "pause": "unistd.h",
        "sleep": "unistd.h",
        "usleep": "unistd.h",
        "exit": "stdlib.h",
    },
    "pipex": {
        "open": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "perror": "stdio.h",
        "strerror": "string.h",
        "access": "unistd.h",
        "dup": "unistd.h",
        "dup2": "unistd.h",
        "execve": "unistd.h",
        "exit": "stdlib.h",

        "fork": "unistd.h",
        "pipe": "unistd.h",
        "unlink": "unistd.h",
        "wait": "sys/wait.h",
        "waitpid": "sys/wait.h",
    },

    "minishell": {
        "readline": "readline.h",
        "rl_clear_history": "readline.h",
        "rl_on_new_line": "readline.h",
        "rl_replace_line": "readline.h",
        "rl_redisplay": "readline.h",
        "add_history": "readline.h",

        "printf": "stdio.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",

        "write": "unistd.h",
        "access": "unistd.h",
        "open": "fcntl.h",
        "read": "unistd.h",
        "close": "unistd.h",

        "fork": "unistd.h",
        "wait": "sys/wait.h",
        "waitpid": "sys/wait.h",
        "wait3": "sys/wait.h",
        "wait4": "sys/wait.h",

        "signal": "signal.h",
        "sigaction": "signal.h",
        "sigemptyset": "signal.h",
        "sigaddset": "signal.h",
        "kill": "signal.h",

        "exit": "stdlib.h",

        "getcwd": "unistd.h",
        "chdir": "unistd.h",

        "stat": "sys/stat.h",
        "lstat": "sys/stat.h",
        "fstat": "sys/stat.h",
        "unlink": "unistd.h",

        "execve": "unistd.h",
        "dup": "unistd.h",
        "dup2": "unistd.h",
        "pipe": "unistd.h",

        "opendir": "dirent.h",
        "readdir": "dirent.h",
        "closedir": "dirent.h",

        "strerror": "string.h",
        "perror": "stdio.h",

        "isatty": "unistd.h",
        "ttyname": "unistd.h",
        "ttyslot": "unistd.h",
        "ioctl": "sys/ioctl.h",

        "getenv": "stdlib.h",

        "tcsetattr": "termios.h",
        "tcgetattr": "termios.h",
        "tgetent": "term.h",
        "tgetflag": "term.h",
        "tgetnum": "term.h",
        "tgetstr": "term.h",
        "tgoto": "term.h",
        "tputs": "term.h",
    },

    "cub3d": {
        "open": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "printf": "stdio.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "perror": "stdio.h",
        "strerror": "string.h",
        "exit": "stdlib.h",

        "sqrt": "math.h",
        "pow": "math.h",
        "fabs": "math.h",
        "sin": "math.h",
        "cos": "math.h",
        "tan": "math.h",

        "mlx_init": "mlx.h",
    },
    "minirt": {
        "open": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "printf": "stdio.h",
        "malloc": "stdlib.h",
        "free": "stdlib.h",
        "perror": "stdio.h",
        "strerror": "string.h",
        "exit": "stdlib.h",

        "sqrt": "math.h",
        "pow": "math.h",
        "fabs": "math.h",
        "sin": "math.h",
        "cos": "math.h",
        "tan": "math.h",

        "mlx_init": "mlx.h",
    },

    "webserv": {
        "execve": "unistd.h",
        "dup": "unistd.h",
        "dup2": "unistd.h",
        "pipe": "unistd.h",
        "strerror": "string.h",
        "gai_strerror": "netdb.h",
        "errno": "sys/errno.h",
        "fork": "unistd.h",

        "htons": "arpa/inet.h",
        "htonl": "arpa/inet.h",
        "ntohs": "arpa/inet.h",
        "ntohl": "arpa/inet.h",

        "select": "sys/select.h",
        "FD_SET": "sys/select.h",
        "poll": "poll.h",
        "epoll": "sys/epoll.h",
        "epoll_create": "sys/epoll.h",
        "epoll_ctl": "sys/epoll.h",
        "epoll_wait": "sys/epoll.h",
        "kqueue": "sys/event.h",
        "kevent": "sys/event.h",

        "socket": "sys/socket.h",
        "socketpair": "sys/socket.h",
        "accept": "sys/socket.h",
        "listen": "sys/socket.h",
        "send": "sys/socket.h",
        "recv": "sys/socket.h",

        "chdir": "unistd.h",
        "bind": "sys/socket.h",
        "connect": "sys/socket.h",
        "getaddrinfo": "netdb.h",
        "freeaddrinfo": "netdb.h",
        "setsockopt": "sys/socket.h",
        "getsockname": "sys/socket.h",
        "getprotobyname": "netdb.h",

        "fcntl": "fcntl.h",
        "close": "unistd.h",
        "read": "unistd.h",
        "write": "unistd.h",
        "waitpid": "sys/wait.h",
        "kill": "signal.h",
        "signal": "signal.h",

        "access": "unistd.h",
        "stat": "sys/stat.h",
        "open": "fcntl.h",
        "opendir": "dirent.h",
        "readdir": "dirent.h",
        "closedir": "dirent.h",
    },
    "irc": {
        "socket": "sys/socket.h",
        "close": "unistd.h",

        "setsockopt": "sys/socket.h",
        "getsockname": "sys/socket.h",
        "getprotobyname": "netdb.h",
        "gethostbyname": "netdb.h",
        "getaddrinfo": "netdb.h",
        "freeaddrinfo": "netdb.h",

        "bind": "sys/socket.h",
        "connect": "sys/socket.h",
        "listen": "sys/socket.h",
        "accept": "sys/socket.h",

        "htons": "arpa/inet.h",
        "htonl": "arpa/inet.h",
        "ntohs": "arpa/inet.h",
        "ntohl": "arpa/inet.h",
        "inet_addr": "arpa/inet.h.h",
        "inet_ntoa": "arpa/inet.h.h",

        "send": "sys/socket.h",
        "recv": "sys/socket.h",
        "signal": "signal.h",
        "sigaction": "signal.h",

        "lseek": "unistd.h",
        "fstat": "sys/stat.h",
        "fcntl": "fcntl.h",
        "poll": "poll.h",
    },
}

writing_systems = {
    "hiragana": {
        "あ": ["a"], "い": ["i"], "う": ["u"], "え": ["e"], "お": ["o"], "か": ["ka"], "が": ["ga"], "き": ["ki"], "ぎ": ["gi"], "く": ["ku"], "ぐ": ["gu"], "け": ["ke"], "げ": ["ge"], "こ": ["ko"], "ご": ["go"], "さ": ["sa"], "ざ": ["za"], "し": ["si", "shi"], "じ": ["zi", "ji"], "す": ["su"], "ず": ["zu"], "せ": ["se"], "ぜ": ["ze"], "そ": ["so"], "ぞ": ["zo"], "た": ["ta"], "だ": ["da"], "ち": ["ti", "chi"], "ぢ": ["di"], "つ": ["tu", "tsu"], "づ": ["du"], "て": ["te"], "で": ["de"], "と": ["to"], "ど": ["do"], "な": ["na"], "に": ["ni"], "ぬ": ["nu"], "ね": ["ne"], "の": ["no"], "は": ["ha"], "ば": ["ba"], "ぱ": ["pa"], "ひ": ["hi"], "び": ["bi"], "ぴ": ["pi"], "ふ": ["hu", "fu"], "ぶ": ["bu"], "ぷ": ["pu"], "へ": ["he"], "べ": ["be"], "ぺ": ["pe"], "ほ": ["ho"], "ぼ": ["bo"], "ぽ": ["po"], "ま": ["ma"], "み": ["mi"], "む": ["mu"], "め": ["me"], "も": ["mo"], "や": ["ya"], "ゆ": ["yu"], "よ": ["yo"], "ら": ["ra"], "り": ["ri"], "る": ["ru"], "れ": ["re"], "ろ": ["ro"], "わ": ["wa"], "ゐ": ["wi"], "ゑ": ["we"], "を": ["wo"], "ん": ["n", "nn"],
    },
    "katakana": {
        "ア": ["a"], "イ": ["i"], "ウ": ["u"], "エ": ["e"], "オ": ["o"], "カ": ["ka"], "ガ": ["ga"], "キ": ["ki"], "ギ": ["gi"], "ク": ["ku"], "グ": ["gu"], "ケ": ["ke"], "ゲ": ["ge"], "コ": ["ko"], "ゴ": ["go"], "サ": ["sa"], "ザ": ["za"], "シ": ["si", "shi"], "ジ": ["zi", "ji"], "ス": ["su"], "ズ": ["zu"], "セ": ["se"], "ゼ": ["ze"], "ソ": ["so"], "ゾ": ["zo"], "タ": ["ta"], "ダ": ["da"], "チ": ["ti", "chi"], "ヂ": ["di"], "ツ": ["tu", "tsu"], "ヅ": ["du"], "テ": ["te"], "デ": ["de"], "ト": ["to"], "ド": ["do"], "ナ": ["na"], "ニ": ["ni"], "ヌ": ["nu"], "ネ": ["ne"], "ノ": ["no"], "ハ": ["ha"], "バ": ["ba"], "パ": ["pa"], "ヒ": ["hi"], "ビ": ["bi"], "ピ": ["pi"], "フ": ["hu", "fu"], "ブ": ["bu"], "プ": ["pu"], "ヘ": ["he"], "ベ": ["be"], "ペ": ["pe"], "ホ": ["ho"], "ボ": ["bo"], "ポ": ["po"], "マ": ["ma"], "ミ": ["mi"], "ム": ["mu"], "メ": ["me"], "モ": ["mo"], "ヤ": ["ya"], "ユ": ["yu"], "ヨ": ["yo"], "ラ": ["ra"], "リ": ["ri"], "ル": ["ru"], "レ": ["re"], "ロ": ["ro"], "ワ": ["wa"], "ヰ": ["wi"], "ヱ": ["we"], "ヲ": ["wo"], "ン": ["n", "nn"],
    },
    "hangul": {
        "ㅏ": ["a"], "ㅐ": ["ae"], "ㅑ": ["ya"], "ㅒ": ["yae"], "ㅓ": ["eo", "ŏ"], "ㅔ": ["e"], "ㅕ": ["yeo", "yŏ"], "ㅖ": ["ye"], "ㅗ": ["o"], "ㅘ": ["wa"], "ㅙ": ["wae"], "ㅚ": ["oe"], "ㅛ": ["yo"], "ㅜ": ["u"], "ㅝ": ["wo", "wŏ"], "ㅞ": ["we"], "ㅟ": ["wi"], "ㅠ": ["yu"], "ㅡ": ["eu", "ŭ"], "ㅢ": ["ui", "ŭi"], "ㅣ": ["i"], "ㄱ": ["g", "k"], "ㄲ": ["kk"], "ㄴ": ["n"], "ㄷ": ["d"], "ㄸ": ["tt"], "ㄹ": ["r", "l"], "ㅁ": ["m"], "ㅂ": ["b", "p"], "ㅃ": ["pp"], "ㅅ": ["s"], "ㅆ": ["ss"], "ㅇ": ["-", "ng"], "ㅈ": ["j", "ch"], "ㅉ": ["jj", "tch"], "ㅊ": ["ch", "ch'"], "ㅋ": ["k", "k'"], "ㅌ": ["t", "t'"], "ㅍ": ["p", "p'"], "ㅎ": ["h"],
    },
}
